### ISSUE TITLE
Manual installation stopped while running. 

### ISSUE THREAD

**Issue by blociss** [cc-hpc-itwm/gpispace#4]
.....
-- Installing: /home/atraore/gpis/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/gpispaces/external/boost/boost_1.63_0/libs/metaparse/doc/predicate.qbk

./install_gpispace.sh: line 16: 137525 Killed                  cmake --install "gpispace-${gpispace_version}/build

**Comment by mzeyen1985** [comment]
GPI-Space doesn't provide an `install_gpispace.sh` script, as such this issue does not belong here.

As mentioned in the [installation instructions](https://www.gpi-space.de/v23.06/installation) and in the [README.md](https://github.com/cc-hpc-itwm/gpispace/blob/main/README.md) file, the recommended way to install GPI-Space is through Spack. The official documentation on how to setup and use Spack is linked there as well.
