### ISSUE TITLE
SPACK_ENV_PATH' is missing

### ISSUE THREAD

**Issue by blociss** [cc-hpc-itwm/gpispace#5]
I installed gpi-space using spack. 
After running this 
```shell
spack load gpi-space
$(spack location -i gpi-space)/share/GPISpace/doc/example/stochastic_with_heureka/selftest
```
I got the following error: 

Any help? 
```shell
[ 17%] Built target stochastic_with_heureka-pnet
[ 20%] Generating gen/pnetc/op/libstochastic_with_heureka.so
[spack cc] ERROR: Spack compiler must be run from Spack! Input 'SPACK_ENV_PATH' is missing.
make[3]: *** [Makefile:90: pnetc/op/stochastic_with_heureka/roll_and_heureka.o] Error 1
make[2]: *** [CMakeFiles/stochastic_with_heureka.pnet-lib.dir/build.make:73: gen/pnetc/op/libstochastic_with_heureka.so] Error 2
make[1]: *** [CMakeFiles/Makefile2:1063: CMakeFiles/stochastic_with_heureka.pnet-lib.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by mrahn** [comment]
Hi blociss, I tried to reproduce but failed.  Can you give more information on the system and how gpi-space got installed?

What worked for me:
```
> git clone -c feature.manyFiles=true https://github.com/spack/spack.git
> . spack/share/spack/setup-env.sh
> spack install gpi-space
> spack load gpi-space
> $(spack location -i gpi-space)/share/GPISpace/doc/example/stochastic_with_heureka/selftest
```

Cheers, Mirko

**Comment by blociss** [comment]
Hello Mirko, 
Here is the whole output. 
![image](https://github.com/cc-hpc-itwm/gpispace/assets/46294807/b3bf3d01-318f-4d80-932a-f0bf2e8503ad)

**Comment by mrahn** [comment]
Cool, thanks. Can you tell me what operation system that is? In order for me to reproduce?

Of the five commands mentioned in https://github.com/cc-hpc-itwm/gpispace/issues/5#issuecomment-1798150608 only four are used in https://github.com/cc-hpc-itwm/gpispace/issues/5#issuecomment-1801328242. Can you retry all 5 commands in a fresh shell, e.g. without any spack installed? What spack version do you use?

```
> spack --version
0.21.0.dev0 (db16335aec9add0ce838f9fcd4eb426352e35b07)
```

**Comment by blociss** [comment]
I remove and reinstall like you stated.  

1.  For  Ubuntu 22.04.3 LTS,( my pc), everything works fine now .
> spack --version
0.21.0.dev0 (ae08b25dacd56b287d8c80ad648b998cfa2ec8cb)

2.  Server Gentoo Linux ( Release:        2.14).
 We wanted also to install it in the server ,  it doesn’t install it.
 here is the output.
 
<img width="1387" alt="image" src="https://github.com/cc-hpc-itwm/gpispace/assets/46294807/d6c21fa6-5425-4138-9599-e2b51425ea8b">

 
<img width="1387" alt="image" src="https://github.com/cc-hpc-itwm/gpispace/assets/46294807/4cfecad9-76de-45c8-a828-c91ff907708b">
